import { NextRequest, NextResponse } from 'next/server'
import { MOCK_RESOURCES } from '@/features/acad/mock-acad-data'
import { UPLOADED_FILES_MAP } from '../mock-upload/route'
import { isSupabaseOnline } from '@/lib/supabase/status'
import { createClient } from '@/lib/supabase/server'

/**
 * Builds a syntactically valid PDF binary with multi-line formatted text.
 */
function generateAcademicPdfBuffer(
  title: string,
  subjectCode: string,
  subjectName: string,
  author: string,
  year: number,
  branch: string,
  type: string
): Buffer {
  const sanitize = (str: string) => str.replace(/[\\()]/g, '')

  const lines: { text: string; size: number; bold?: boolean; dy?: number }[] = [
    { text: `CAMPUS ACADEMIC REPOSITORY`, size: 10, dy: 16 },
    { text: sanitize(title), size: 16, bold: true, dy: 24 },
    { text: `Subject: ${sanitize(subjectCode)} - ${sanitize(subjectName)}`, size: 11, bold: true, dy: 18 },
    { text: `Program: Year ${year} | ${sanitize(branch)} | Document Type: ${sanitize(type.toUpperCase())}`, size: 10, dy: 16 },
    { text: `Uploaded By: ${sanitize(author)} | Verified Campus Academic Resource`, size: 9, dy: 22 },
    { text: `------------------------------------------------------------------------------------------------`, size: 9, dy: 20 },
    { text: `1. COURSE OVERVIEW & CORE OBJECTIVES`, size: 12, bold: true, dy: 20 },
    { text: `This document contains lecture notes, algorithmic implementations, formal theorems,`, size: 10, dy: 15 },
    { text: `and past examination problems curated for undergraduate engineering coursework.`, size: 10, dy: 15 },
    { text: `Key learning targets include complexity analysis, memory safety, dynamic allocation,`, size: 10, dy: 15 },
    { text: `optimal query planning, and asymptotic bounds for time and space resources.`, size: 10, dy: 22 },
    { text: `2. FUNDAMENTAL CONCEPTS & COMPLEXITY ANALYSIS`, size: 12, bold: true, dy: 20 },
    { text: `- Balanced Search Structures: AVL and Red-Black Trees maintain height O(log n).`, size: 10, dy: 15 },
    { text: `- Graph Algorithms: Dijkstra with min-priority queue runs in O((V + E) log V).`, size: 10, dy: 15 },
    { text: `- Shortest Path in DAGs: Topological sort followed by single-pass relaxation in O(V + E).`, size: 10, dy: 15 },
    { text: `- Dynamic Programming: Optimal substructure and overlapping subproblems with memoization.`, size: 10, dy: 15 },
    { text: `- Relational Normalization: 1NF through BCNF to minimize redundancy and anomaly risks.`, size: 10, dy: 22 },
    { text: `3. HIGH-YIELD PRACTICE QUESTIONS FOR EXAMINATIONS`, size: 12, bold: true, dy: 20 },
    { text: `Q1: Prove that any comparison-based sorting algorithm requires at least Omega(n log n) operations.`, size: 10, dy: 15 },
    { text: `Q2: Construct the AVL tree resulting from inserting keys: 15, 20, 24, 10, 13, 7, 30, 36, 25.`, size: 10, dy: 15 },
    { text: `Q3: Explain the difference between B-Trees and B+ Trees with respect to range query efficiency.`, size: 10, dy: 15 },
    { text: `Q4: Describe ACID properties in transaction management and how WAL guarantees Durability.`, size: 10, dy: 22 },
    { text: `------------------------------------------------------------------------------------------------`, size: 9, dy: 20 },
    { text: `Generated by Campus Super-App Academic Module. Verified for student study & AI flashcards.`, size: 8, dy: 16 },
  ]

  let stream = ''
  let currentY = 770

  for (const item of lines) {
    currentY -= item.dy ?? 16
    const fontRef = item.bold ? '/F2' : '/F1'
    stream += `BT ${fontRef} ${item.size} Tf 50 ${currentY} Td (${item.text}) Tj ET\n`
  }

  const streamBytes = Buffer.from(stream, 'utf-8')
  const streamLen = streamBytes.length

  const objects: string[] = []
  objects[1] = '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj'
  objects[2] = '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj'
  objects[3] =
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>\nendobj'
  objects[4] = '4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj'
  objects[5] = '5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj'
  objects[6] = `6 0 obj\n<< /Length ${streamLen} >>\nstream\n${stream}endstream\nendobj`

  let offset = 0
  let pdfOut = '%PDF-1.4\n'
  offset = Buffer.byteLength(pdfOut, 'utf-8')

  const xrefOffsets: number[] = [0]
  for (let i = 1; i <= 6; i++) {
    xrefOffsets[i] = offset
    pdfOut += objects[i] + '\n'
    offset = Buffer.byteLength(pdfOut, 'utf-8')
  }

  const startXref = offset
  pdfOut += 'xref\n0 7\n0000000000 65535 f \n'
  for (let i = 1; i <= 6; i++) {
    pdfOut += String(xrefOffsets[i]).padStart(10, '0') + ' 00000 n \n'
  }
  pdfOut += 'trailer\n<< /Size 7 /Root 1 0 R >>\n'
  pdfOut += `startxref\n${startXref}\n%%EOF\n`

  return Buffer.from(pdfOut, 'utf-8')
}

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url)
  const resourceId = searchParams.get('id')

  if (!resourceId) {
    return NextResponse.json({ error: 'Missing resource ID' }, { status: 400 })
  }

  // 1. Check in-memory store for newly uploaded files in this session
  const cachedUpload = UPLOADED_FILES_MAP.get(resourceId)
  if (cachedUpload) {
    return new Response(new Uint8Array(cachedUpload.buffer), {
      headers: {
        'Content-Type': cachedUpload.contentType,
        'Content-Disposition': `attachment; filename="${encodeURIComponent(cachedUpload.fileName)}"`,
        'Cache-Control': 'public, max-age=3600',
      },
    })
  }

  // 2. Resolve resource metadata (from DB or mock)
  let resource: {
    id: string
    title: string
    storage_path?: string
    file_ext?: string
    year?: number
    branch?: string
    type?: string
    subject?: { code?: string; name?: string }
    uploader?: { full_name?: string }
  } | null = null

  if (await isSupabaseOnline()) {
    try {
      const supabase = await createClient()
      const { data } = await supabase
        .from('resources')
        .select(`
          *,
          subject:subjects(code, name),
          uploader:profiles!resources_uploader_id_fkey(full_name)
        `)
        .eq('id', resourceId)
        .single()
      if (data) resource = data

      // If remote Supabase storage has the file, stream it
      if (resource?.storage_path) {
        const { data: fileData, error: downloadErr } = await supabase.storage
          .from('resources')
          .download(resource.storage_path)

        if (!downloadErr && fileData) {
          const buffer = await fileData.arrayBuffer()
          const filename = `${resource.title.replace(/[^a-zA-Z0-9_\-\.]/g, '_')}.${resource.file_ext || 'pdf'}`
          return new Response(buffer, {
            headers: {
              'Content-Type': resource.file_ext === 'pdf' ? 'application/pdf' : 'application/octet-stream',
              'Content-Disposition': `attachment; filename="${filename}"`,
              'Cache-Control': 'public, max-age=3600',
            },
          })
        }
      }
    } catch {
      // Fall through to mock generator
    }
  }

  // Fallback to MOCK_RESOURCES
  if (!resource) {
    const mock = MOCK_RESOURCES.find((r) => r.id === resourceId)
    if (mock) resource = mock
  }

  const title = resource?.title || 'Course Material Notes'
  const fileExt = resource?.file_ext || 'pdf'
  const filename = `${title.replace(/[^a-zA-Z0-9_\-\.]/g, '_')}.${fileExt}`

  const pdfBuffer = generateAcademicPdfBuffer(
    title,
    resource?.subject?.code || 'CS201',
    resource?.subject?.name || 'Data Structures and Algorithms',
    resource?.uploader?.full_name || 'Prof. Rajesh Sharma',
    resource?.year || 2,
    resource?.branch || 'Computer Science',
    resource?.type || 'notes'
  )

  return new Response(new Uint8Array(pdfBuffer), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Content-Length': String(pdfBuffer.length),
      'Cache-Control': 'public, max-age=3600',
    },
  })
}
